<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
	  <PackageReference Include="MassTransit" Version="8.2.1" />
	  <PackageReference Include="MediatR" Version="13.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Modulith.Commerce.AdminUser.Domain\Modulith.Commerce.AdminUser.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\Modulith.Commerce.Common.Application\Modulith.Commerce.Common.Application.csproj" />
    <ProjectReference Include="..\..\..\Common\Modulith.Commerce.Common.Auth\Modulith.Commerce.Common.Auth.csproj" />
    <ProjectReference Include="..\..\..\Contracts\Modulith.Commerce.AdminUsers.IntegrationEvents\Modulith.Commerce.AdminUsers.IntegrationEvents.csproj" />
  </ItemGroup>

</Project>
